name: ftw_fieldmapper
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pytorch=2.3.* 
  - torchvision
  - pytorch-cuda=12.1 
  - cuda-toolkit=11.8    
  - torchmetrics
  - torchgeo    
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - scikit-image
  - opencv
  - rasterio
  - rioxarray
  - geopandas  
  - pyarrow          
  - kornia
  - ipykernel
  - ipywidgets          
  - pip                
  - pip:
      - segmentation_models_pytorch==0.4.*
