name: ftw_fieldmapper
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - rasterio
  - rioxarray
  - geopandas  
  - pyarrow 
  - pytorch=2.3.*        
  - torchvision
  - pytorch-cuda=12.1
  - torchmetrics
  - torchgeo           
  - kornia
  - ipykernel
  - ipywidgets          
  - pip                
  - pip:
      - segmentation_models_pytorch==0.4.*
